apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-verifier
  namespace: default
  labels:
    app: receipt-verifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt-verifier
  template:
    metadata:
      labels:
        app: receipt-verifier
    spec:
      containers:
      - name: receipt-verifier
        image: coilhq/receipt-verifier:main
